default:
  log_level: 'DEBUG'                                      # Optional values: TRACE, DEBUG, INFO, WARN...
  outer_n_folds: 10                                       # Number of folds in cross-validation
  outer_n_repeats: 10                                      # Number of cross-validation repetitions
  tuning_n_folds: 10                                      # If hyper-parameter tuning enabled, number of inner folds for tuning
  tuning_n_repeats: 1                                     # If hyper-parameter tuning enabled, number of CV repeats for tuning
  use_tune_grid: false                                    # If true, uses grid-search for hyperparameter tuning. Otherwise uses Bayes
  cluster_type: 'clustering99'                            # Can also be: "none"
  ranger_n_threads: 4                                    # Number of threads for random forest training
  params_combo: {                                         # A list of all pipeline parameters to check (will create all possible combinations)
    'should_tune': [false],                               # Tuning: false, true, or both
    'should_shuffle': [false, true],                      # Add label shuffling to get null models to compare to
    'fs_type': ['Boruta90'], # Feature selection type. Other options: 'pertBoruta', 'Boruta80'
  }
  disease_labels: ['disease'] # All labels to consider as the "disease" group study
  unknown_taxa: ['(UG)']  
  paths: {
    'ml_input_dir': 'data/ml_input',
    'ml_output_dir': 'data/ml_output',
    'results_tables_dir': 'data/ml_output/results_tables',
    'logs_dir': 'data/ml_output/logs',              # Relevant for run_pipeline_parallel.R only
    'ko_names': 'db/kegg/ko_to_name_map_partial.txt',
    'humann_uniref_ko_map': 'db/humann/map_ko_uniref90_long.txt',
    'metacyc_pathways_hierarchy': 'db/metacyc/metacyc_pathway_db.txt',
    'metacyc_pathways2taxa': 'db/metacyc/All-pathways-of-MetaCyc-and-their-associated-species.txt', 
    'metacyc_bacterial_taxa': 'db/metacyc/MetaCyc-bacteria.txt', 
    'combined_cv_results': 'data/ml_output/results_tables/cv_results_all_datasets.csv',
    'combined_feature_importance': 'data/ml_output/results_tables/feature_importance_all_datasets.tsv',
    'results_rdata': 'data/ml_output/results_tables/results_for_analysis.RData'
  }
  paths_templates: { # %s indicated dataset name
    'all_data_preprocessed': 'data/ml_input/%s/all_data.tsv',
    'metadata': 'data/ml_input/%s/metadata.tsv',
    'taxonomy': 'data/ml_input/%s/taxonomy.tsv',
    'pathways': 'data/ml_input/%s/pathways.tsv',
    'metabolites': 'data/ml_input/%s/metabolites.tsv',
    'metagenome': 'data/ml_input/%s/KOs.tsv',
    'log': 'data/ml_output/logs/%s_ml_pipeline.log', # Relevant for run_pipeline_parallel.R only
    'feature_importance_csv': 'data/ml_output/results_tables/%s_feature_importance.csv',
    'cv_results_csv': 'data/ml_output/results_tables/%s_pipeline.csv',
    'raw_oof_predictions': 'data/ml_output/results_tables/%s_oof_predictions.csv'
  }
  params_short_names: {
    'should_tune': {'FALSE': '-T', 'TRUE': '+T'},
    'should_shuffle': {'FALSE': '-Sh', 'TRUE': '+Sh'},
    'fs_type': {'none': '-FS', 'Boruta90': '+FS_B90', 'Boruta80': '+FS_B80', 'utest': '+FS_U', 'ensemble': '+FS_ENS', 'pertBoruta': '+FS_PB90', 'RepeatBoruta90': '+FS_RB90', 'altmann': '+FS_A', 'altmann_top20': '+FS_A20'}
  }
  
test:
  outer_n_repeats: 2
  outer_n_folds: 10
  ranger_n_threads: 4
  params_combo: {
    'should_tune': [false],
    'should_shuffle': [false], 
    'fs_type': ['Boruta90']
  }
